jobs:
  build:
    # checkout repository
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

    # set branch name variable
    - name: Set branch name variable
      id: vars
      run: echo ::set-output name=branchName::${GITHUB_REF##*/}

    - name: Echo current branch
      run: echo "The current branch is ${{ steps.vars.outputs.branchName }}"

    # bump version and push tag
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      id: versionBump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: ${{ env.Branches }}
        DEFAULT_BUMP: minor
        WITH_V: false
    - run: echo "The new version is ${{ steps.versionBump.outputs.new_tag }}"

    # replace text in package.json
    - name: replace version text
      shell: pwsh
      run: (Get-Content -path package.json -Raw) -replace "version patch","version ${{ steps.versionBump.outputs.new_tag }} --no-git-tag-version -f" | Set-Content -Path package.json

    # run npm commands
    - uses: actions/setup-node@v2
      with:
        node-version: 12
        registry-url: ${{ env.NPMRegistry }}

    # install npm dependencies from package-lock.json
    - name: npm install
      run: ${{ env.InstallCommand }}
      
    # build npm
    - name: npm build
      run: ${{ env.BuildCommand }}

    # publish github artifacts
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.organization.name }}-${{ github.event.repository.name }}
        path: ${{ env.Output }}
