name: Build GitHub Artifact

on:
  push:
    branches: [{{Branch}}]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: {{NPMRegistry}}

      - name: NPM Install
        run: {{InstallCommand}}

      - name: NPM Publish
        run: {{BuildScript}}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: {{Organization}}-{{Repository}}
          path: {{OutputFolder}}
