name: Publish to NPM

on:
  push:
    branches: [{{Branch}}]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: {{NPMRegistry}}
      - name: NPM Install
        run: npm install
      - name: NPM Publish
        run: {{PublishScript}}
        env:
          NODE_AUTH_TOKEN: {{NPM_TOKEN}}
